name: Build EDK2 Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential acpica-tools nasm uuid-dev gcc-aarch64-linux-gnu

      - name: Clone EDK2, EDK2-non-osi, and EDK2-platforms
        run: |
          export WORKSPACE="$(pwd)/build"
          mkdir $WORKSPACE
          cd $WORKSPACE
          git clone https://github.com/tianocore/edk2.git
          pushd edk2
          git checkout 46f4c9677c615d862649459392f8f55b3e6567c2
          popd
          git clone https://github.com/tianocore/edk2-non-osi.git
          pushd edk2-non-osi
          git checkout 1e2ca640be54d7a4d5d804c4f33894d099432de3
          popd
          git clone https://github.com/tianocore/edk2-platforms.git
          pushd edk2-platforms
          git checkout 861c200cda1417539d46fe3b1eba2b582fa72cbb
          popd
          git clone https://github.com/andreiw/rk3399-edk2.git edk2-platforms/Platform/Rockchip

      - name: Set environment variables
        run: |
          ls
          pwd
          tree
          export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
          export PACKAGES_PATH=$WORKSPACE/edk2:$WORKSPACE/edk2-platforms:$WORKSPACE/edk2-non-osi
          . $WORKSPACE/edk2/edksetup.sh

      - name: Compile BaseTools
        run: make -C $WORKSPACE/edk2/BaseTools

      - name: Build UEFI firmware
        run: build -a AARCH64 -t GCC5 -p $WORKSPACE/edk2-platforms/Platform/Rockchip/Rk3399Pkg/Rk3399-SDK.dsc -b DEBUG -n $(nproc)

      - name: Create loader image
        run: $WORKSPACE/edk2-platforms/Platform/Rockchip/Rk3399Pkg/Tools/loaderimage --pack --uboot $WORKSPACE/Build/Rk3399-SDK/DEBUG_GCC5/FV/RK3399_SDK_UEFI.fd $WORKSPACE/RK3399_SDK_UEFI.img

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Firmware Artifacts
          path: |
            $WORKSPACE/RK3399_SDK_UEFI.img
